import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  page: {
    display: "flex",
    flexDirection: "column",
    gap: 0,
  } satisfies CSSProperties,
  header: {
    padding: "24px 32px 16px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  pageTitle: {
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  readOnlyNotice: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginTop: 6,
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  headerActions: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 8,
  } satisfies CSSProperties,
  statusLine: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "380px 1fr",
    gap: 20,
    padding: "0 32px 44px",
    minHeight: 0,
    alignItems: "start",
  } satisfies CSSProperties,
  listCol: {
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  filterInput: {
    margin: 12,
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  showing: {
    padding: "0 16px 8px",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100vh - 260px)",
    overflowY: "auto",
  } satisfies CSSProperties,
  row: (active: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 16px",
    borderTop: "1px solid var(--border)",
    borderLeft: "none",
    borderRight: "none",
    borderBottom: "none",
    cursor: "pointer",
    background: active ? "var(--accent-bg)" : "transparent",
    textAlign: "left",
    width: "100%",
  }),
  rowPath: (active: boolean): CSSProperties => ({
    fontSize: 12.5,
    color: active ? "var(--accent-text)" : "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  rowMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  chip: (c: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: "1px 7px",
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 600,
    color: c,
    background: bg,
  }),
  excludedMarker: {
    color: "var(--crit)",
    fontWeight: 600,
  } satisfies CSSProperties,
  viewerCol: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 24,
    minHeight: 300,
  } satisfies CSSProperties,
  viewerPath: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginBottom: 14,
  } satisfies CSSProperties,
} as const;
