import type { CSSProperties } from "react";

/** Co-located styles for the BlastRadius card + Tree/Graph sub-views. */
export const s = {
  statRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 12,
  } satisfies CSSProperties,
  viewToggle: {
    display: "flex",
    gap: 6,
    marginBottom: 12,
  } satisfies CSSProperties,
  explanation: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: 0,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  partialNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    border: "1px solid var(--warn)",
    borderRadius: 6,
    padding: "8px 10px",
    marginBottom: 12,
    lineHeight: 1.4,
  } satisfies CSSProperties,
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  symbolRow: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  } satisfies CSSProperties,
  symbolHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    cursor: "pointer",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  symbolName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolKind: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  symbolBody: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "10px 12px",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  callerList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
  } satisfies CSSProperties,
  callerSymbol: {
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  truncatedHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  factChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  } satisfies CSSProperties,
  factGroupLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  priorPrsToggle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 0",
  } satisfies CSSProperties,
  priorPrList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 8,
  } satisfies CSSProperties,
  priorPrRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    fontSize: 12.5,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  priorPrMeta: {
    color: "var(--text-muted)",
    fontSize: 12,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  graphEmpty: {
    fontSize: 13,
    color: "var(--text-muted)",
    padding: "24px 0",
    textAlign: "center",
  } satisfies CSSProperties,
} as const;
